### ISSUE TITLE
New function for validation middleware for express ?

### ISSUE THREAD

**Issue by fipartners** [mafintosh/is-my-json-valid#10]
Is it an improvement to make a function or a new npm next to this one to link the schema validator with a validation middleware Express like this lib
https://www.npmjs.com/package/isvalid-express (or another one)

**Comment by mafintosh** [comment]
Not completely sure what you mean. Do you wan't to make an express middleware library? If so, sure go head :)

**Comment by fipartners** [comment]
yes I will do it
