### ISSUE TITLE
Available as bower module for client side use?

### ISSUE THREAD

**Issue by codeofsumit** [mafintosh/is-my-json-valid#103]
Is this awesome library available for client side use via `bower install`.

**Comment by mafintosh** [comment]
You can use browserify the to use it as a client side module

**Comment by dirakkk** [comment]
as far as i am concerned I have an issue in client side with the directive var validator = require('is-my-json-valid/require') and browserify 

--->require.js:5 Uncaught TypeError: require.resolve is not a function

**Comment by yoshuawuyts** [comment]
@dirakkk could you open a separate issue for this with a more intricate example? Ideally a repro would be grand. I'm closing this issue as the initial post seems resolved (e.g. use `npm` + `browserify`, we're not going to support `bower`). Cheers!

**Comment by dirakkk** [comment]
@yoshuawuyts Sorry about that , but I am precisely talking about browserify use of is-my-json-valid.
I simply write var validator = require('is-my-json-valid/require') and when I load the index.html page with the browserify bundle.js included , I get the following error:
--->require.js:5 Uncaught TypeError: require.resolve is not a function

**Comment by yoshuawuyts** [comment]
[is-my-json-valid runs fine in the browser](http://requirebin.com/?gist=9b7cece074fc5932878d01b127166ff8). Could you create a repro? I'm happy to assist you a little bit, but I need more to work with. Cheers

**Comment by dirakkk** [comment]
thanks a lot @yoshuawuyts 
just to give a first hint , I am already using browserify in this project and it is ok , i am also using it in node.js and it is ok.



The problem happens in this case:
I have a file called index.html that calls bundle.js that is created from example.js with the following command

`"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "browserify public/scripts/example.js -o public/scripts/bundle.js",
    "start": "watchify public/scripts/example.js -o public/scripts/bundle.js -v -d |node server.js"
  }`

In example.js I am requiring a local js file calles commentList.js with the following command (and it works)

`var CommentList=require ('./commentList');`

In this commentList.js file I require IMJV with the following command

`var validator = require('is-my-json-valid/require');`

And just with that ,without using IMJV after !  I have the following error

 --->require.js:5 Uncaught TypeError: require.resolve is not a function

seems like the pb comes from the line from require.js->
`delete require.cache[require.resolve(__filename)]`

What do you think ? should I set __filename somewhere ?

**Comment by yoshuawuyts** [comment]
eh, yeah you might not want to do `require('is-my-json-valid/require')`, as it relies on `fs`. Perhaps you'd like to give [brfs](https://github.com/substack/brfs) a shot; but probably the solution is to avoid it all together. I hope this was somewhat helpful

**Comment by dirakkk** [comment]
thanks man , it works with brfs.
By the way , I just followed the documentation
`Optionally you can use the require submodule to load a schema from __dirname

var validator = require('is-my-json-valid/require')
var validate = validator('my-schema.json')`

So I believe it could be interesting to fix this issue . I  am a newbyer so I cannot do it myself right now.
What do you and the rest of the team think ?
