### ISSUE TITLE
Nested additionalProperties isn't respected

### ISSUE THREAD

**Issue by LinusU** [mafintosh/is-my-json-valid#109]
Example schema:

```javascript
{
  type: 'object',
  properties: {
    data: {
      type: 'object',
      additionalProperties: true
    }
  },
  required: [
    'data'
  ],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-04/schema#'
}
```

Example data:

```javascript
{
  "data": {
    "test": "I should be allowed!"
  }
}
```

This is rejected by is-my-json-valid with the following error:

```javascript
[ { field: 'data', message: 'has additional properties' } ]
```

**Comment by LinusU** [comment]
Okay, it turns out that I was a bit off, guess that's what I guess for jumping to conclusions to fast.

The problem was that the object I validated actually looked like this:

```javascript
{
  "id": "0ebcd4bb-a721-46b6-bcb8-85276fbc75f3",
  "data": {
    "test": "I should be allowed!"
  }
}
```

So the real problem seems to be that the field get's reported as `data` instead of `id`...

**Comment by LinusU** [comment]
Also, the following schema:

```javascript
{
  type: 'object',
  properties: {},
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-04/schema#'
}
```

with the same data:

```javascript
{
  "id": "0ebcd4bb-a721-46b6-bcb8-85276fbc75f3",
  "data": {
    "test": "I should be allowed!"
  }
}
```

Gives to errors with the same field:

```javascript
[ { field: 'data', message: 'has additional properties' },
  { field: 'data', message: 'has additional properties' } ]
```

**Comment by LinusU** [comment]
Okay, I'm just spewing out confusion today :laughing: 

The problem has nothing to do with my field named `data`. Rather, is-my-json-valid names the root to `data`. I do feel that this is very confusing though.

I wouldn't actually have found myself in this situation if either one of #84 or #102 would have been implemented, so I'm going to close this one in favour of those.

If anyone read this, thank you for your time, hopefully it provided some amusement :)

**Comment by mafintosh** [comment]
@LinusU haha no worries
