### ISSUE TITLE
Split schemas and references

### ISSUE THREAD

**Issue by skilledDeveloper** [mafintosh/is-my-json-valid#11]
Does it support split schemas and references? 
(Something like https://github.com/tdegrunt/jsonschema)

**Comment by watson** [comment]
If you are referring to `$ref` support, then yes

**Comment by skilledDeveloper** [comment]
Yes $ref is working within an schema but how can I refer to an external  schema?
For example:
```
var emailSchema = {id: "#email", type: "string", format: "email"},
  mySchema = {type: "object", $ref: "#email" },
  validate = validator(...);
```
How can I refer to emailSchema from mySchema?

**Comment by mafintosh** [comment]
We could support an array of additional schemas to fix this.

```
var validate = validator(mySchema, [emailSchema])
```

@watson thoughts?

**Comment by watson** [comment]
@mafintosh what about the 2nd options argument where you specify formats? If we want to support both at the same time we might instead look for a `schemas` parameter to the options hash:

```js
var validate = validator(mySchema, { schemas: [...] })
```

Also, if I understand the spec correctly, we need to associate each external schema with a `$ref` key - correct?

In that case we might want to change the `schemas` array to a key/value hash instead. I can try and cook up a PR if you like

**Comment by mafintosh** [comment]
oh yea. your thing is better. so

``` js
var validate = validator(mySchema, { schemas: {'#email': emailSchema }}) ?
```

**Comment by Muscula** [comment]
You can see how all the other JSON validators do this in this file:
https://github.com/Muscula/json-schema-benchmark/blob/master/index.js
For inspiration?
They all use something like
```js
validator.addSchema(id, schema)
```
I'm not saying that's how you should do it of course - just for inspiration. The `#` in `#email` seems unnecessary in your example.

**Comment by skilledDeveloper** [comment]
Either way will work. My personal preference is using a single argument for validate method. This can be either an schema object (like what it is) or an array of schemas.

``` javascript
var validate = validator(someSchema);  //a single schema
var validate = validator([mySchema, emailSchema]); //array of schemas that referring each other 
```

**Comment by Muscula** [comment]
The array of schemas doesn't correspond very well with the official JSON Schema tests. They will require a bit of special coding to run. The premise ther is that the validator runs one main schema, that refers to others. You could of corse have a convention that the first schema in the array is the main one that you will be validating against.

But then I kind of like mafintosh'es suggestion better.

Implementing this will mean that more of the official JSON schema tests will turn green for `is-my-json-valid` - by the way.

**Comment by th0r** [comment]
Is there any way to workaround this issue for now? What about something like this:
```js
var userIdDefinition = {
    definitions: {
        userId: {
            type: 'number'
        }
    }
};

var userValidator = validator(merge({
    title: 'User object',
    type: 'object',
    properties: {
        userId: { $ref: '#/definitions/userId' },
        name: {
            required: true,
            type: 'string'
        }
    }
}, userIdDefinition));
```
But how effective it is with a lot of additional definitions merged?

**Comment by mafintosh** [comment]
This `schemas` option is now supported in 2.4.0. Checkout the docs here, https://github.com/mafintosh/is-my-json-valid#external-schemas and let me know what you think :)

**Comment by skilledDeveloper** [comment]
Cool thanks.
Does it support "id" property?
```
var ext = {
  id: 'extId'
  required: true,
  type: 'string'
}
```

**Comment by Muscula** [comment]
I still have the official ref tests failing, even after adding the refs:
https://github.com/Muscula/json-schema-benchmark/blob/master/index.js#L32
Have you tested the solution against the official tests?

**Comment by mafintosh** [comment]
@Muscula does that test except imjv to download the schema from the remote url?

**Comment by Muscula** [comment]
@mafintosh no. The other schema validators, that support ref, work fine sync. when passed those refs. with addSchema (or similar)
https://github.com/Muscula/json-schema-benchmark/blob/master/index.js#L70

**Comment by mafintosh** [comment]
Ah ok. I understand it now. I'll fix that.
