### ISSUE TITLE
undefined bypasses validation

### ISSUE THREAD

**Issue by julien-f** [mafintosh/is-my-json-valid#116]
```js
const assert = require('assert')

const validate = require('is-my-json-valid')({
  type: 'string'
})

// Works.
assert(validate(''))
assert(!validate(null))
assert(!validate({}))

// Does not work.
assert(!validate(undefined))
```

**Comment by yoshuawuyts** [comment]
Could it be because the value isn't set as required?

**Comment by julien-f** [comment]
How could it be marked as required?

Only object properties can be optional (and therefore marked as required when necessary)…

**Comment by julien-f** [comment]
JSON schema spec is so confusing :stuck_out_tongue:

**Comment by julien-f** [comment]
AFAICT, the ability to set the `required` flag directly in a schema is an *is-my-json-valid* extension, therefore it breaks my use case :confused:

**Comment by yoshuawuyts** [comment]
Oh, that's interesting hah - so I always thought that the top level definition was 'object', and then properties had to be appended to it. If the top level is just a single value of `string` then it perhaps isn't required by default? 

I believe there's two ways of defining required values, the `required` field being the latest. Brain is fudge, bed time now - hope this was somehow helpful haha

**Comment by yoshuawuyts** [comment]
no no `required: true` should be non-recommended behavior at worst, don't believe it's non-standard tho

**Comment by julien-f** [comment]
The behavior is identical for any types:

```js
const validate = require('is-my-json-valid')({
  type: 'object'
})
assert(validate(undefined))
```

**Comment by emilbayes** [comment]
Maybe it's because `undefined` is not a valid JSON value?

> A JSON value can be an object, array, number, string, true, false, or null.

**Comment by julien-f** [comment]
Hmm, it makes sense but IMHO, `validate`as a function taking a Javascript value (not a JSON string), I would except it to behave nicely.

**Comment by julien-f** [comment]
@emilbayes Thanks mate!
