### ISSUE TITLE
How to deal with Objects in Array? / Is there an option for property limits?

### ISSUE THREAD

**Issue by mo-mueller** [mafintosh/is-my-json-valid#117]
I have this json format for books:

```
{
  "name": "Harry Potter", 
  "author": "Joanne K. Rowling",
  "libraries": [
      {"id": 1}, 
      {"id": 2}
  ]
}
```

How can I validate this? I mean specifically the "libraries" part. I tried it like this:

```
var validate = validator({
        required: true,
        type: 'object',
        properties: {
            name: {
                required: true,
                type: 'string'
            },
            author: {
                required: true,
                type: 'string'
            },
            libraries: {
                required: true,
                type: 'array',
                properties: {
                    id: {
                        required: true,
                        type: 'number'
                    }
                },
                additionalProperties: false
            }
        },
        additionalProperties: false
});
```

But I get the message:

> [ { field: 'data.libraries.id', message: 'is required' } ]

And then I have another question:

Is it possible to set a limit for properties? That I cant write "name" two times, for example?

**Comment by LinusU** [comment]
It's very possible to this today 🎉 

```js
{
  $schema: 'http://json-schema.org/draft-04/schema#',
  type: 'object',
  additionalProperties: false,
  properties: {
    name: {
      type: 'string'
    },
    author: {
      type: 'string'
    },
    libraries: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          id: {
            type: 'number'
          }
        },
        required: [
          'id'
        ]
      }
    }
  },
  required: [
    'name',
    'author',
    'libraries'
  ]
}
```

**Comment by sr3k4nth** [comment]
> I have this json format for books:
> 
> ```
> {
>   "name": "Harry Potter", 
>   "author": "Joanne K. Rowling",
>   "libraries": [
>       {"id": 1}, 
>       {"id": 2}
>   ]
> }
> ```
> 
> How can I validate this? I mean specifically the "libraries" part. I tried it like this:
> 
> ```
> var validate = validator({
>         required: true,
>         type: 'object',
>         properties: {
>             name: {
>                 required: true,
>                 type: 'string'
>             },
>             author: {
>                 required: true,
>                 type: 'string'
>             },
>             libraries: {
>                 required: true,
>                 type: 'array',
>                 properties: {
>                     id: {
>                         required: true,
>                         type: 'number'
>                     }
>                 },
>                 additionalProperties: false
>             }
>         },
>         additionalProperties: false
> });
> ```
> 
> But I get the message:
> 
> > [ { field: 'data.libraries.id', message: 'is required' } ]
> 
> And then I have another question:
> 
> Is it possible to set a limit for properties? That I cant write "name" two times, for example?

  libraries: {
            required: true,
            type: 'array',
            items: {
                id: {
                    required: true,
                    type: 'number'
                }
            }
        }
