### ISSUE TITLE
Throws TypeError for types email and date-time

### ISSUE THREAD

**Issue by onury** [mafintosh/is-my-json-valid#126]
When the schema includes an item with type `email` or `date-time`, it will throw this:
`TypeError: types[(t || "any")] is not a function`

(Actually it will throw this for invalid types but `email` and `date-time` are valid types as per JSON-schema v4.)

**Comment by LinusU** [comment]
Actually, `email` and `date-time` aren't valid _types_, the are formats. Use them as follows:

```js
{
  type: 'object',
  properties: {
    email: { type: 'string', format: 'email' },
    birth: { type: 'string', format: 'date-time' }
  }
}
```

I hope this solves your issue 👌
