### ISSUE TITLE
Add IMJV to json-schema.org implementations page

### ISSUE THREAD

**Issue by skilledDeveloper** [mafintosh/is-my-json-valid#13]
I would be nice to see IMJV in this page:
http://json-schema.org/implementations.html

Here is the page source code:
https://github.com/json-schema/json-schema/blob/gh-pages/implementations.html

**Comment by Muscula** [comment]
I created apull request for that 3 days ago:
https://github.com/json-schema/json-schema/pull/152

**Comment by skilledDeveloper** [comment]
Cool.
I will close this issue.

**Comment by Muscula** [comment]
Leave a comment on the pull request saying you would like to see it merged :-)
