### ISSUE TITLE
`minLength` ignored for items of array type?

### ISSUE THREAD

**Issue by AJB99** [mafintosh/is-my-json-valid#136]
Hi there, another excellent mafintosh lib. I use `mongojs` on the daily. You've got a knack for UX.

I've run into an issue (bug?) when evaluating the `minLength` of any given array being validated. Consider the following:
```
var validate = validator({
    type: 'object',
    required: true,
    additionalProperties: false,
    properties: {
        pages : {
            type : 'array',
            required : true,
            minLength : 3,
            items : {
                type : 'object',
                additionalProperties : false,
                properties : {
                    title : {
                        type : 'string',
                        required : true
                    },
                    url : {
                        type : 'string',
                        required : true
                    }
                }
            }
        }
    }
}, {
    verbose : true
})

var data = {
    pages : [
        { title : 1, url : 'http://someurlhere.com' },
        { title : 2, url : 'http://someotherurlhere.com' }
    ]
}

var valid = validate(data); // true
if (validate.errors) {
    console.log(validate.errors)
}
```

I would expect this to throw since I've declared `minLength: 3` for the `pages` array. But it passes even though I'm only sending two items through on the `data` object.

Is this the expected behaviour?

Additionally, when passing an empty array, the data validates just fine when I'm expecting an empty array to throw. Is this also the expected behaviour?

```
var data = {
    pages : []
}

var valid = validate(data); // true
```

Thanks for any light you can shed on this!

**Comment by LinusU** [comment]
This indeed seems like a bug, smaller test case:

https://runkit.com/5817cf4da433260014a11fe3/5882877ada465a00141b97a6/branches/master

```js
var validator = require('is-my-json-valid')

var validate = validator({
  type: 'array',
  items: { type: 'string' },
  minLength: 3
})

console.log(`this should be false: ${validate(['a', 'b'])}`)
```

**Comment by AJB99** [comment]
I actually found the issue. It's not a bug, I just got the keyword wrong. It should be `minItems` instead of `minLength`:

https://runkit.com/5882e034402ada0014424d44/5882e034402ada0014424d45

```
var validator = require('is-my-json-valid')

var validate = validator({
  type: 'array',
  items: { type: 'string' },
  minItems: 3
})

console.log(`this should be false: ${validate(['a', 'b'])}`)
```

**Comment by LinusU** [comment]
Cool 👍
