### ISSUE TITLE
Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by kmlamplia** [mafintosh/is-my-json-valid#154]
Hello, I updated my project with the last version, and it has a error

Cannot read property 'concat' of undefined
    at visit path/node_modules/is-my-json-valid/index.js:366:69)
    at path/node_modules/is-my-json-valid/index.js:416:9
    at Array.forEach (native)
    at visit (path/node_modules/is-my-json-valid/index.js:409:18)
    at path/node_modules/is-my-json-valid/index.js:543:9
    at Array.forEach (native)

**Comment by LinusU** [comment]
Hello, this was an error in version `2.17.0` and has now been fixed in `2.17.1`, see #149 for more details. Sorry for any inconvenience.
