### ISSUE TITLE
Content-Security-Policy Issue with is-my-json-valid dependency

### ISSUE THREAD

**Issue by Chinna-A** [mafintosh/is-my-json-valid#185]
<div type='discussions-op-text'>

We have Content-Security-Policy for the project, facing issue with sub dependency (generate-function (index.js)) throwing unsafe eval exception. Can you please help on this

![image](https://user-images.githubusercontent.com/54196967/129579891-69939235-b911-405f-be54-b2e0194e6e56.png)
</div>

**Comment by LinusU** [comment]
This library works by dynamically creating functions that validates input. In order to use this you need to make sure that this is allowed by your content-security-policy...
