### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by MichielDeMey** [mafintosh/is-my-json-valid#19]
Hi

How would you feel about adding the option for the validation to happen asynchronous as opposed to synchronous?

It's already fast as-is, but an async API would be amazing as it won't block the running code.

Thanks!

**Comment by Muscula** [comment]
Why do you want it not to block?
When the code does no I/O it kind of does not make sense to do a callback. Unless you spin up a new process, and that would be a very heavy process. You could  probably do this yourself by using child_process.fork and message passing if you really want to.

**Comment by watson** [comment]
@MichielDeMey as @Muscula say, there is no part of the validation that does I/O, so I don't see the benefint. Can you supply a use case?

**Comment by MichielDeMey** [comment]
No specific use-case, I simply prefer to use callbacks, mostly in conjunction with the async module.

As a bonus, you can easily promisify these for users who prefer to use promises.

But I agree, the optimization is not necessary as JavaScript is single-threaded anyway and no I/O is happening.

**Comment by watson** [comment]
@MichielDeMey Adding a callback for this reason is not normal within js and will confuse most people, but thanks for the feedback - it's highly appreciated :)
