### ISSUE TITLE
patternProperties error field has an extra `]`

### ISSUE THREAD

**Issue by plievone** [mafintosh/is-my-json-valid#21]
Invalid patternProperties result in `{ field: 'data.*]', message: 'is the wrong type' }` (notice the extra `]`). It seems that `formatName()` is called with `'data[keys1[i]]'` and so it returns `'data.*]'`.

Maybe it could somehow push the tested key name in error message instead of globbing.

**Comment by mafintosh** [comment]
Fixed in 2.6.0 (by #26)

**Comment by mafintosh** [comment]
Thanks for reporting this! :+1:
