### ISSUE TITLE
What is the reason for formatName()

### ISSUE THREAD

**Issue by danieljuhl** [mafintosh/is-my-json-valid#23]
I have a JSON schema (and some data sets) which has ' ' (space) in the property name.

When validator find an error in one of these keys, in shows the property name as * (star), eg. 
```
{
  field: 'data.*',
  message: 'pattern mismatch
}
```

I'd hoped for the validator to return `field: 'data["some key with a space"]'`.

What is the reason for using formatName? Is the idea to show the index of an array as a star instead of the actual index, or?

**Comment by mafintosh** [comment]
yes we should show the actual index.
the errors messages are gonna get updated in a future version.

**Comment by mafintosh** [comment]
Fixed in 2.6.0 (by #26)
