### ISSUE TITLE
Output the value on error

### ISSUE THREAD

**Issue by danieljuhl** [mafintosh/is-my-json-valid#24]
For now I've made a little function which iterates the errors and add the value from the validated data set, to each error. Wouldn't it be a nice enhancement to is-my-json-valid? Maybe added using a flag when creating the validator, like the newly added filter-flag.

The output I use is:
```
{
  field: 'data.size',
  message: 'is less than minimum',
  value: 0
}
```

It makes it faster to investigate the errors in the data set.

**Comment by mafintosh** [comment]
we should probably call this `verbose` mode or something. anyways if you are up for it send me a pr that adds this :+1:

**Comment by danieljuhl** [comment]
I'll make a PR right away...

**Comment by danieljuhl** [comment]
@mafintosh Any updates or questions on this? I have another PR almost ready, which fixes the missing field names when required properties is defined as an array, but it's build on this PR and the one you've just accepted.

**Comment by mafintosh** [comment]
@danieljuhl added a small comment to your pr. let me know what you think
