### ISSUE TITLE
Multiple validation in the same validade(...)

### ISSUE THREAD

**Issue by filipedeschamps** [mafintosh/is-my-json-valid#30]
Hi guys! Great module, specially on how the errors object is returned!

So, is there anyway to validate all rules at the same time, including all the rules for the same property? As I can see, is-my-json-valid is making validation in batches.

**Comment by mafintosh** [comment]
I'm not sure what you mean. Could you give me an example?

**Comment by filipedeschamps** [comment]
Sure @mafintosh thanks for the fast reply!

## Schema
``` javascript
  var schema = {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 100
      },
      "slug": {
        "type": "string",
        "minLength": 100
      }
    },
    "required": ["title", "slug"],
    "additionalProperties": false
  };
```

## Validation 1 (ok)
**data**
``` javascript
{}
```

**result**
``` javascript
[ { field: 'data.title', message: 'is required' },
  { field: 'data.slug', message: 'is required' } ]

```

## Validation 2 (not ok)
**data**
``` javascript
{
     title: 'less then 100 characters'
}
```

**result**
``` javascript
[ { field: 'data.slug', message: 'is required' } ]
```
**expected**

``` javascript
[ { field: 'data.title', message: 'has less length than allowed' },
  { field: 'data.slug', message: 'is required' } ]
```

## Validation 3 (ok)
**data**
``` javascript
{
     title: 'less then 100',
     slug: 'also less then 100'
}
```

**result**
``` javascript
[ { field: 'data.title', message: 'has less length than allowed' },
  { field: 'data.slug', message: 'has less length than allowed' } ]
```


## Conclusion
Looks like it will only get to formatting validation once all required values where fulfilled?

**Comment by mafintosh** [comment]
I can reproduce. Confirmed.

**Comment by andreypopp** [comment]
Just hit this issue.

Unfortunately this makes `is-my-json-valid` unusable for validating forms in browser cause it is confusing to user that there are no errors and then after other required fields are ok — errors appear.

Would be awesome to see this fixed.
