### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by RGBboy** [mafintosh/is-my-json-valid#32]
I really like the API of this library over the other json scheme validation libraries. Just wondering if browser support is going to be considered?

**Comment by filipedeschamps** [comment]
Hi!

I'm using it without any trouble with browserify.

**Comment by mafintosh** [comment]
Like @filipedeschamps it already works in the browser using browserify or something like https://wzrd.in

**Comment by RGBboy** [comment]
OK thanks. I tried to run the tests in the browser but they fail because of fs.readdirsync calls and then dynamic fs.readfilesync calls. Would you mind if I made a pull request so that the tests can be run without using those API's?

Also what would be your take on adding cross browser tests as part of the development process? Perhaps making use of testling?

**Comment by mafintosh** [comment]
@RGBboy oh right. a pr that fixes that would be great! also a browser ci is a good idea. i've heard good things about https://saucelabs.com/opensauce/ so maybe we should check that out as testling tends to be a bit unstable these days.
