### ISSUE TITLE
Integer type is broken between 2^31 and 2^53

### ISSUE THREAD

**Issue by pesho** [mafintosh/is-my-json-valid#35]
The validation fails for integer values between 2^31 and 2^53 (`is-my-json-valid` does not think these values are integers).

Examples:
`2147483647` - integer (correct)
`2147483648` - not an integer (fail)
`9007199254740992` - not an integer (fail)
`9007199254740994` - integer (correct)

This is especially significant, because the values currently returned by `Date.now()` are in that range.

**Comment by mafintosh** [comment]
Thanks for reporting this. A fix is released in 2.9.2

**Comment by pesho** [comment]
Awesome, thanks :+1:
