### ISSUE TITLE
support JavaScript plain Date objects as date-time.

### ISSUE THREAD

**Issue by jon49** [mafintosh/is-my-json-valid#61]
Is it possible to support a Date object? Since once I `JSON.stringify` the date it will be a proper date, but before then I would like to use it as a date object. Maybe when checking if it is date-time if it is not a string try and `JSON.stringify` then check it?

Is there another way around this?

**Comment by chrahunt** [comment]
Can you give a little more information about your particular use case like where validated objects are coming from, a simplified schema, and how validation is used in what you're trying to do?

**Comment by chrahunt** [comment]
Without feedback I'm going to close this.
