### ISSUE TITLE
Recursively filter object

### ISSUE THREAD

**Issue by jon49** [mafintosh/is-my-json-valid#62]
Currently it doesn't seem like nested objects/arrays are supported for the filter functionality. This would be really useful. When I have time I'll try and implement it. But if anyone else gets to it before me that would be great!

**Comment by ebdrup** [comment]
We're using it in production to filter nested elements, works fine for us. But you have to use `additinalProperties:false` on sub-object for it to work. And it can't filter in `oneOf`-constructions

**Comment by jon49** [comment]
OK, not sure what I was doing, because it is actually working on a different object of mine. I ended up not need to do it since mongoose does filtering also. If I run into this problem again I'll make sure all my ts are crossed and see if I still come up with this problem.

Thanks for your help.
