### ISSUE TITLE
URI schema resolver

### ISSUE THREAD

**Issue by jwueller** [mafintosh/is-my-json-valid#66]
Currently, external schemata are ignored. Example:

    { "$ref": "http://example.org/schema/definitions.json#/definitions/uuid" }

I would propose something along the lines of this:

    var validate = validator(schema, {
        schemaUriResolver: function(uri, callback) {
             // uri is "http://example.org/schema/definitions.json", excluding the fragment
             http.get(uri, function(res) {
                 callback(JSON.parse(res.body));
             });
        }
    });

This would obviously require some restructuring of the code, since it is not async-compatible at the moment. 

Alternatively, it would be great if we could accept top-level schemata instead of duplicating all sub-schema paths when providing those up-front.

Any thoughts?

**Comment by chrahunt** [comment]
The implementation in #69 doesn't change the current behavior [here](https://github.com/mafintosh/is-my-json-valid/blob/master/index.js#L8) which I believe would still break your example. Wasn't sure if it would be proper to remove that line since I'm not sure why it is there.
