### ISSUE TITLE
Error when reading property of JSON that may be null.

### ISSUE THREAD

**Issue by chrahunt** [mafintosh/is-my-json-valid#72]
While reviewing the comment [here](https://github.com/mafintosh/is-my-json-valid/issues/22#issue-57316566) on #22, I came across a bug where we try to read the properties of a possible `null` value.

This can be recreated with the following on 2.12.0:

```javascript
var validator = require('is-my-json-valid');

var validate = validator({
  "type": ["null", "object"],
  "properties": {
    "example": { "type": "string" }
  }
});

validate(null);
```

**Comment by Matt-Esch** [comment]
It seems that is-my-json-valid doesn't respect the type array, I have just run into this bug

**Comment by btknorr** [comment]
This is a show stopper for us...any idea when this will be fixed?

**Comment by jamesedwardcooke** [comment]
Submitted a PR [here](https://github.com/mafintosh/is-my-json-valid/pull/86).

**Comment by emilbayes** [comment]
This seems to have been resolved with @ghost PR
