### ISSUE TITLE
Feature request: Make it easy to add schema extensions

### ISSUE THREAD

**Issue by Muscula** [mafintosh/is-my-json-valid#8]
We would like to add som schema extensions.
For example if a property has `maxDecimals:2`, we would like to verify that the number has at most two decimal digits (currency). We would also like to add special handlers for when the `format` is set to `date` or `date-time`.
The module [themis](https://www.npmjs.com/package/themis). Has a way or registering special formats that looks nice (It also has a way of registering custom validators like the maxDecimals):
```js
Themis.registerFormat('username', function (str) {
  return /^[a-zA-Z0-9_\.-]+$/.test(str);
});
```

**Comment by Muscula** [comment]
Come to think of it. We could do the maxDecimals:2 with a `format:currency` for numbers. So `registerFormat`, would be enough if it works for both string and numbers.

**Comment by mafintosh** [comment]
In 2.1.0 you can add custom formats as the `formats` option on compile time. 

https://github.com/mafintosh/is-my-json-valid#custom-formats

**Comment by Muscula** [comment]
Does it also allow you to specify a function to vaildate instead of just a regExp. Because a regexp validating a date is kind of hard, with days in month, leap years etc. 

Can you do something like: 
```js
{format: { test:function(value){  }}}
```

Is the format also applied to numbers?

**Comment by mafintosh** [comment]
In 2.2.0 you now can.
It is applied anywhere in the schema and on any type where you provide `format: 'my-custom-format'`
