### ISSUE TITLE
Remote external references

### ISSUE THREAD

**Issue by kgryte** [mafintosh/is-my-json-valid#83]
What is the motivation behind not resolving remote external references? See [here](https://github.com/mafintosh/is-my-json-valid/blob/master/index.js#L8).

This prevents using complex schemas which reference external resources out-of-the-box (i.e., without having to preprocess a schema with find-and-replace). Based on the JSON schema [specification](http://json-schema.org/latest/json-schema-core.html#anchor27), remote references are allowed. 

From the looks of things, [jsonpointer](https://github.com/janl/node-jsonpointer/blob/master/jsonpointer.js) follows the [IETF](http://tools.ietf.org/html/draft-ietf-appsawg-json-pointer-08) specification. But the JSON schema specification suggests that remote resources are permitted.

Any insight into the design decision?

This is related to #66.

**Comment by chrahunt** [comment]
@mafintosh if that specific line was just a stand-in for handling remote references without failing, we can remove it. That would allow the PR that handled #66 to further handle remote references via schema retrieved and passed using the `ext` option.

@kgryte removing that line would allow for users to retrieve remote schema themselves and just pass them in the `ext` option. So for #66, the solution would be:

```javascript
var remote_schema = "http://example.org/schema/definitions.json";

http.get(remote_schema, function(res) {
  var validate = validator(schema, {
    ext: {
      "http://example.org/schema/definitions.json": JSON.parse(res.body)
    }
  });
});
```

If you have a schema where you don't know the referenced remote schema ahead of time, it could be dealt with by iterating over the schema object and retrieving `$ref`d resources and then passing them in the same way. Is that sufficient?

**Comment by kgryte** [comment]
Yes, that should suffice. Thanks for the reply!

**Comment by kgryte** [comment]
Thanks!
