### ISSUE TITLE
Date validation?

### ISSUE THREAD

**Issue by reyesdiego** [mafintosh/is-my-json-valid#90]
Sorry, is it possible to validate Dates, but not using the "format", or am I missing something?. Thanks

**Comment by yoshuawuyts** [comment]
You can use the type `string` with the format `date-time` for that, as defined by [`RFC3339`](http://tools.ietf.org/html/rfc3339).

## See Also
- [RFC3339](http://tools.ietf.org/html/rfc3339)
- [understanding-json-schema/string](http://spacetelescope.github.io/understanding-json-schema/reference/string.html)

**Comment by chrahunt** [comment]
As @yoshuawuyts states, since JSON itself doesn't have a concept of "Dates" separate from strings, this is the approach that should be used.
