### ISSUE TITLE
Feature request: line numbers on error

### ISSUE THREAD

**Issue by braco** [mafintosh/is-my-json-valid#97]
Would be nice to use as a linter.

**Comment by yoshuawuyts** [comment]
@braco Could you provide some more details, I'm not quite sure what you mean. Thanks!

**Comment by braco** [comment]
"line 15 of foo.json: error message"

as opposed to just the json path.

this would allow the validator to be used in text editors to lint arbitrary json formats, including the json schema itself.

**Comment by emilbayes** [comment]
I think this is outside the scope of this module. The validator takes parsed JSON as input, and therefore has no concept of how the source file is laid out. You could make a module that maps `is-my-json-valid` errors to line numbers in a json file, since you have the full JSON pointer.
