### ISSUE TITLE
recursive definitions aren't handled correctly

### ISSUE THREAD

**Issue by mattanbi** [mafintosh/is-my-json-valid#99]
Hi,
in cases like:
"properties": {
        "pages": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/page"
      }
    }
  },

  "definitions": {
...
"page": {
      "type": "object",
      "additionalProperties": false
      "properties": {
        "pages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/page"
          }
        }
      }
    }
...

this json will return an error about additional properties in the 3rd "pages" sub object. Expected no error since there aren't any additional properties;
"obj1": {
		"pages": [
			{
				"pages": [
					{
						"pages": [
							{
								
							}
						]
					}
				]
			}
		]

**Comment by yoshuawuyts** [comment]
It's quite hard to see what's going on. Can you fix the formatting? thanks

**Comment by yoshuawuyts** [comment]
Closing because there are not enough details to work with. Feel free to post a more accurate description if you want it to be reopened. Thanks!
